name: Frontend CI

on:
  pull_request:
    branches:
      - feature/*
      - develop
  push:
    branches:
      - feature/*
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 18
  PNPM_VERSION: 8

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  UITest:
    name: "UI テスト"
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check
        run: git status

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # 任意のNode.jsバージョン


      - name: Install dependencies
        run: npm install

      - name: install chrome
        run: npx puppeteer browsers install chrome

      - name: build storybook
        run: npm run build-storybook

      - name: star storybook
        run: npm run server-storybook &

      - name: storycap
        run: npx storycap http://localhost:6006

      - name: mv
        run: mkdir -p .reg

      - name: mv
        run: mv __screenshots__ .reg/expected

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check
        run: git status

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # 任意のNode.jsバージョン

      - name: Restore npm cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: npm install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: install chrome
        run: npx puppeteer browsers install chrome

      - name: storycap
        run: npm run storycap

      - name: reg-suit
        run: npx reg-suit compare -v
