name: visual regression testing

on: [push]

jobs:
  vrt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git fetch --prune --unshallow
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Use Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: npm install, build, and test
        run: npm install
      - name: workaround for detached HEAD
        run: |
          git checkout ${GITHUB_REF#refs/heads/} || git checkout -b ${GITHUB_REF#refs/heads/} && git pull
      - name: storybook build
        run: npm run build-storybook
      # - name: storybook start
      #   run: npm run ci:storybook
      - name: screenshot and visual regression test
        run: |
          npm run ci:screenshot
          npm run ci:vrt